TRUNCATE TABLE courses RESTART IDENTITY CASCADE;
TRUNCATE TABLE lessons RESTART IDENTITY CASCADE;
TRUNCATE TABLE groups  RESTART IDENTITY CASCADE;

INSERT INTO courses VALUES (1, 'IT');
INSERT INTO groups VALUES (1, 'A12');